### sse subscribe
GET {{host}}/notification/subscribe
Authorization: {{token}}


### notification redirect
GET {{host}}/notification/2
Authorization: {{token}}

### unread notifications
GET {{host}}/notification
Authorization: {{token}}