### sse subscribe
GET {{host}}/notification/subscribe/d6c62de89f4e4d4faa3e643a743e9311
Authorization: {{token}}

### notification redirect
GET {{host}}/notification/2
Authorization: {{token}}

### unread notifications
GET {{host}}/notification
Authorization: {{token}}